name: myfeelings
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter Community Plus Plugins
  device_info_plus: ^9.1.0
  package_info_plus: ^8.0.0
  connectivity: ^3.0.6

  # 상태관리
  flutter_riverpod: ^2.1.3

  # json
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0

  # 권한
  permission_handler: ^10.4.3

  # storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # 네트워크
  dio: ^5.4.3+1

  # ui
  flutter_svg: ^2.0.3
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30

  # bottom_ui
  awesome_bottom_bar: ^1.2.4

  # splash
  flutter_native_splash: ^2.3.1

  # 애니메이션
  animations: ^2.0.11

  #utils
  velocity_x: ^4.1.1
  flutter_screenutil: ^5.9.0
  logger: ^2.4.0
  intl: ^0.19.0

  #webview
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  freezed: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icon/svg/
    - assets/images/
    - assets/images/logo/
    - assets/json/
    - assets/json/licenses.json


  fonts:
    - family: Chab
      fonts:
        - asset: assets/fonts/chab/chab.ttf
          weight: 700


    - family: Elice_Digital_Baeum
      fonts:
        - asset: assets/fonts/elice_digital_baeum/EliceDigitalBaeum_Bold.ttf
          weight: 700
        - asset: assets/fonts/elice_digital_baeum/EliceDigitalBaeum_Regular.ttf
          weight: 400

    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Thin.ttf
          weight: 100

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf

    - family: Sebang
      fonts:
        - asset: assets/fonts/sebang/SEBANG Gothic.ttf
          weight: 300
        - asset: assets/fonts/sebang/SEBANG Gothic Bold.ttf
          weight: 500

      # 바텀 네비게이션 아이콘
    - family: BottomIcon
      fonts:
        - asset: assets/icon/BottomIcon.ttf
